#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running format and lint checks before push..."
pnpm fix

if [ $? -ne 0 ]; then
  echo "❌ Format or lint errors found. Please fix them before pushing."
  exit 1
fi

echo "✅ All checks passed!"
